---

- name: Install SSH server packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ssh_server_packages }}"

- name: Merge default and custom SSH server config
  set_fact:
    ssh_server_config: "{{ _ssh_server_config_default | combine(ssh_server_config, recursive = True) }}"
  notify: SSH server configuration

- name: Create Ansible local facts directory
  file:
    path: /etc/ansible/facts.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create ssh_local_facts dictionary
  set_fact:
    ssh_local_facts:
      ssh_host_keys_rebuilt: "{{ hostvars[inventory_hostname] | json_query('ansible_local.ssh.ssh_host_keys_rebuilt') | default('no', 'yes') | bool }}"
      ssh_moduli_rebuilt: "{{ hostvars[inventory_hostname] | json_query('ansible_local.ssh.ssh_moduli_rebuilt') | default('no', 'yes') | bool }}"

- block:

    - name: Rebuild DH group exchange candidate primes
      command:
        /usr/bin/ssh-keygen -G "/etc/ssh/moduli.{{ ssh_moduli_bits}}.all" -b "{{ ssh_moduli_bits }}"
      args:
        creates: "/etc/ssh/moduli.{{ ssh_moduli_bits }}.all"

    - name: Test DH group exchange candidate primes for safety
      command:
        /usr/bin/ssh-keygen -T "/etc/ssh/moduli.{{ ssh_moduli_bits}}.safe" -f "/etc/ssh/moduli.{{ ssh_moduli_bits }}.all"
      args:
        creates: "/etc/ssh/moduli.{{ ssh_moduli_bits}}.safe"

    - name: Install new DH group exchange candidate primes
      copy:
        src: "/etc/ssh/moduli.{{ ssh_moduli_bits }}.safe"
        dest: /etc/ssh/moduli
        force: yes
        remote_src: yes
        owner: root
        group: root
        mode: 0644
      notify: Restart SSH

  always:

    - name: Remove DH group exchange candidate primes intermediate files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/ssh/moduli.{{ ssh_moduli_bits }}.all"
        - "/etc/ssh/moduli.{{ ssh_moduli_bits }}.safe"

  when: ssh_rebuild_moduli and not ssh_local_facts.ssh_moduli_rebuilt

- block:

    - name: Get key files in /etc/ssh
      shell: ls /etc/ssh/ssh_host_*key*
      register: ssh_host_key_files

    - name: Remove old host keys
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ ssh_host_key_files.stdout_lines }}"

    - name: Rebuild host key
      command:
        "/usr/bin/ssh-keygen -t {{ item.key }} -b {{ item.value }} -f /etc/ssh/ssh_host_{{ item.key }}_key -N ''"
      args:
        creates: "/etc/ssh/ssh_host_{{ item.key }}_key*"
      with_dict: "{{ ssh_host_keys_bits }}"

  when: ssh_rebuild_host_keys and not ssh_local_facts.ssh_host_keys_rebuilt

- name: Build HostKey configuration option
  set_fact:
    ssh_host_key_config: "/etc/ssh/ssh_host_{{ item.key }}_key"
  register: ssh_host_key_config_result
  with_dict: "{{ ssh_host_keys_bits }}"

- name: Build HostKey list
  set_fact:
    ssh_host_key_config: "{{ ssh_host_key_config_result.results | map(attribute = 'ansible_facts.ssh_host_key_config') | list }}"

- name: Add HostKey to SSH server config
  set_fact:
    ssh_server_config: "{{ ssh_server_config | combine({ 'HostKey': ssh_host_key_config }) }}"
  notify:
    - SSH server configuration
    - Restart SSH

- name: Build HostKeyAlgorithms configuration option
  set_fact:
    ssh_host_key_algorithms_config: "ssh-{{ item.key }}"
  register: ssh_host_key_algorithms_config_result
  with_dict: "{{ ssh_host_keys_bits }}"

- name: Build HostKeyAlgorithms list
  set_fact:
    ssh_host_key_algorithms_config: "{{ ssh_host_key_algorithms_config_result.results | map(attribute = 'ansible_facts.ssh_host_key_algorithms_config') | list | join(',') }}"

- name: Add HostKeyAlgorithms to SSH server config
  set_fact:
    ssh_server_config: "{{ ssh_server_config | combine({ 'HostKeyAlgorithms': ssh_host_key_algorithms_config }) }}"
  notify:
    - SSH server configuration
    - Restart SSH
  with_dict: "{{ ssh_host_keys_bits }}"

- name: Update ssh_local_facts
  set_fact:
    ssh_local_facts_update:
      ssh_host_keys_rebuilt: "{{ ssh_rebuild_host_keys }}"
      ssh_moduli_rebuilt: "{{ ssh_rebuild_moduli }}"

- name: Merge ssh_local_facts with updated version
  set_fact:
    ssh_local_facts: "{{ ssh_local_facts | combine(ssh_local_facts_update, recursive = True) }}"

- name: Persist ssh_local_facts
  template:
    src: ssh.fact.j2
    dest: /etc/ansible/facts.d/ssh.fact
    owner: root
    group: root
    mode: 0644

- name: SSH server configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart SSH

- name: Enable and start SSH server
  service:
    name: ssh
    enabled: yes
    state: started
