---

- name: Install SSH server packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ssh_server_packages }}"

- name: Merge default and custom SSH server config
  set_fact:
    ssh_server_config: "{{ _ssh_server_config_default | combine(ssh_server_config, recursive = True) }}"
  notify: SSH server configuration

- block:

    - name: Rebuild DH group exchange candidate primes
      command:
        /usr/bin/ssh-keygen -G "/etc/ssh/moduli.{{ ssh_moduli_bits}}.all" -b "{{ ssh_moduli_bits }}"
      args:
        creates: "/etc/ssh/moduli.{{ ssh_moduli_bits }}.all"
      changed_when: no

    - name: Test DH group exchange candidate primes for safety
      command:
        /usr/bin/ssh-keygen -T "/etc/ssh/moduli.{{ ssh_moduli_bits}}.safe" -f "/etc/ssh/moduli.{{ ssh_moduli_bits }}.all"
      args:
        creates: "/etc/ssh/moduli.{{ ssh_moduli_bits}}.safe"
      changed_when: no

    - name: Install new DH group exchange candidate primes
      copy:
        src: "/etc/ssh/moduli.{{ ssh_moduli_bits }}.safe"
        dest: /etc/ssh/moduli
        force: yes
        remote_src: yes
        owner: root
        group: root
        mode: 0644
      changed_when: no
      notify: Restart SSH

  always:

    - name: Remove DH group exchange candidate primes intermediate files
      file:
        path: "{{ item }}"
        state: absent
      changed_when: no
      with_items:
        - "/etc/ssh/moduli.{{ ssh_moduli_bits }}.all"
        - "/etc/ssh/moduli.{{ ssh_moduli_bits }}.safe"

  when: ssh_rebuild_moduli

- block:

    - name: Get key files in /etc/ssh
      shell: ls /etc/ssh/ssh_host_*key*
      register: ssh_host_key_files
      changed_when: no

    - name: Remove old host keys
      file:
        path: "{{ item }}"
        state: absent
      changed_when: no
      with_items: "{{ ssh_host_key_files.stdout_lines }}"

    - name: Rebuild host key
      command:
        "/usr/bin/ssh-keygen -t {{ item.key }} -b {{ item.value }} -f /etc/ssh/ssh_host_{{ item.key }}_key -N ''"
      args:
        creates: "/etc/ssh/ssh_host_{{ item.key }}_key*"
      changed_when: no
      with_dict: "{{ ssh_host_keys_bits }}"

    - name: Build HostKey configuration option
      set_fact:
        ssh_host_key_config: "/etc/ssh/ssh_host_{{ item.key }}_key"
      register: ssh_host_key_config_result
      with_dict: "{{ ssh_host_keys_bits }}"

    - name: Build HostKey list
      set_fact:
        ssh_host_key_config: "{{ ssh_host_key_config_result.results | map(attribute = 'ansible_facts.ssh_host_key_config') | list }}"

    - name: Add HostKey to SSH server config
      set_fact:
        ssh_server_config: "{{ ssh_server_config | combine({ 'HostKey': ssh_host_key_config }) }}"
      changed_when: no
      notify:
        - SSH server configuration
        - Restart SSH

    - name: Build HostKeyAlgorithms configuration option
      set_fact:
        ssh_host_key_algorithms_config: "ssh-{{ item.key }}"
      register: ssh_host_key_algorithms_config_result
      with_dict: "{{ ssh_host_keys_bits }}"

    - name: Build HostKeyAlgorithms list
      set_fact:
        ssh_host_key_algorithms_config: "{{ ssh_host_key_algorithms_config_result.results | map(attribute = 'ansible_facts.ssh_host_key_algorithms_config') | list | join(',') }}"

    - name: Add HostKeyAlgorithms to SSH server config
      set_fact:
        ssh_server_config: "{{ ssh_server_config | combine({ 'HostKeyAlgorithms': ssh_host_key_algorithms_config }) }}"
      changed_when: no
      notify:
        - SSH server configuration
        - Restart SSH

  when: ssh_rebuild_host_keys

- name: SSH server configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart SSH

- name: Enable and start SSH server
  service:
    name: ssh
    enabled: yes
    state: started
