---

- name: Install SSH client packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ssh_client_packages }}"

- name: Merge default and custom SSH client config
  set_fact:
    ssh_client_config: "{{ _ssh_client_config_default | combine(ssh_client_config, recursive = True) }}"

- name: SSH client configuration
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
