---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: debian-stretch
    image: debian:stretch
    dockerfile_tpl: debian-systemd
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
    volumes:
      - /run/sshd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  options:
    disable-pytest-warnings: True
    v: True
  lint:
    name: flake8
